version: '3'
services:
  # go:
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #   command: /bin/sh -c "go run main.go"
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 8000:8000
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080
  # volumes:
  #   db-data:
  #     driver: local
